version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install application
          command: sudo su -c "./llv2_build.sh -y 3"
      - run:
          name: Test xAPI
          command: ./tests/checkURL.sh -u localhost/data/xAPI/about
      - run:
          name: Test API
          command: ./tests/checkURL.sh -u localhost/api
      - run:
          name: Test UI
          command: ./tests/checkURL.sh -u localhost
      - run:
          name: Get logs
          command: |
            cat /var/log/learninglocker/install.log
            cat /var/log/learninglocker/xapi_stdout*.log
            cat /var/log/learninglocker/api_stdout*.log
            cat /var/log/learninglocker/ui_stdout*.log
            cat /var/log/learninglocker/worker_stdout*.log
            cat /var/log/learninglocker/xapi_stderr*.log
            cat /var/log/learninglocker/api_stderr*.log
            cat /var/log/learninglocker/ui_stderr*.log
            cat /var/log/learninglocker/worker_stderr*.log